-- MySQL Script generated by MySQL Workbench
-- Mon Jul 30 19:05:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prueba_reclut
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prueba_reclut
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prueba_reclut` DEFAULT CHARACTER SET utf8 ;
USE `prueba_reclut` ;

-- -----------------------------------------------------
-- Table `prueba_reclut`.`beneficiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba_reclut`.`beneficiario` (
  `idbeneficiario` INT NOT NULL AUTO_INCREMENT,
  `nombre_beneficiario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idbeneficiario`),
  UNIQUE INDEX `idbeneficiario_UNIQUE` (`idbeneficiario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba_reclut`.`naturaleza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba_reclut`.`naturaleza` (
  `idnaturaleza` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idnaturaleza`),
  UNIQUE INDEX `idnaturaleza_UNIQUE` (`idnaturaleza` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba_reclut`.`facturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba_reclut`.`facturacion` (
  `id_facturacion` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(40) NOT NULL,
  `fecha` DATE NOT NULL,
  `idbeneficiario` INT NOT NULL,
  `salida` VARCHAR(45) NOT NULL,
  `saldo` VARCHAR(45) NOT NULL,
  `banco` VARCHAR(15) NOT NULL,
  `tipo_mov` VARCHAR(15) NOT NULL,
  `empresa` VARCHAR(15) NOT NULL,
  `idnaturaleza` INT NOT NULL,
  PRIMARY KEY (`id_facturacion`, `idbeneficiario`, `idnaturaleza`),
  INDEX `fk_facturacion_beneficiario_idx` (`idbeneficiario` ASC),
  INDEX `fk_facturacion_naturaleza1_idx` (`idnaturaleza` ASC),
  UNIQUE INDEX `id_facturacion_UNIQUE` (`id_facturacion` ASC),
  CONSTRAINT `fk_facturacion_beneficiario`
    FOREIGN KEY (`idbeneficiario`)
    REFERENCES `prueba_reclut`.`beneficiario` (`idbeneficiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturacion_naturaleza1`
    FOREIGN KEY (`idnaturaleza`)
    REFERENCES `prueba_reclut`.`naturaleza` (`idnaturaleza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
